# Generated by Django 3.1.13 on 2021-11-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_majorrequirement_major_req_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='majorrequirement',
            unique_together={('major_id', 'description', 'major_req_title')},
        ),
    ]
