# Generated by Django 3.1.13 on 2021-10-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferevaluation',
            unique_together={('transfer_course_id', 'major_req_id')},
        ),
    ]
