# Generated by Django 3.1.13 on 2021-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20211024_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorrequirement',
            name='major_req_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
